version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - ./insert.sql:/docker-entrypoint-initdb.d/insert.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "dbProduto"
    ports:
      - "9090:5432"